# Generated by Django 3.1.3 on 2020-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('slug', models.CharField(default='', max_length=1000)),
                ('sellername', models.CharField(default='', max_length=100)),
                ('pickuplocation', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=50000)),
                ('name', models.CharField(max_length=900)),
                ('email', models.CharField(max_length=1101)),
                ('address', models.CharField(max_length=1101)),
                ('city', models.CharField(max_length=1101)),
                ('state', models.CharField(max_length=1101)),
                ('zip_code', models.CharField(max_length=1011)),
                ('phone', models.CharField(default='', max_length=1011)),
            ],
        ),
        migrations.CreateModel(
            name='TrackUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=900)),
                ('update', models.CharField(default='', max_length=9000)),
                ('daysleft', models.CharField(default='', max_length=9000)),
            ],
        ),
    ]
